sudo: required

env:
  global:
  - CHKIT_VERSION=v3.5.1
  - IMAGE_NAME=containerum/kdc-docs
  - CONTAINERUM_API="https://panel.api.containerum.io"
  - NAMESPACE=containerum-kdc-docs

services:
  - docker

install:
  - wget https://github.com/containerum/chkit/releases/download/${CHKIT_VERSION}/chkit_linux_amd64_${CHKIT_VERSION}.tar.gz
  - tar -zxf chkit_linux_amd64_${CHKIT_VERSION}.tar.gz && sudo mv chkit /bin/chkit

script:
  - chkit set api ${CONTAINERUM_API}
  - chkit login -u ${CONTAINERUM_LOGIN} -p ${CONTAINERUM_PASSWORD} -n -
  - docker build -t "$IMAGE_NAME" --build-arg DOCS_COMMIT="${TRAVIS_COMMIT::8}" .
  - echo "Commit ${TRAVIS_COMMIT::8}"

before_deploy:
  - docker login -u="$DOCKER_LOGIN" -p="$DOCKER_PASSWORD"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:release"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:dev"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_COMMIT::8}"
  - if [ "$TRAVIS_TAG" ]; then docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_TAG}"; fi

deploy:
  - provider: script
    script: docker push "${IMAGE_NAME}:dev" && docker push "${IMAGE_NAME}:${TRAVIS_COMMIT::8}"
    skip_cleanup: true
    on:
      branch: develop
  - provider: script
    script: chkit set image --deployment docs-dev --image "${IMAGE_NAME}:${TRAVIS_COMMIT::8}" --force -n ${NAMESPACE}
    skip_cleanup: true
    on:
      branch: develop

  - provider: script
    script: docker push "${IMAGE_NAME}:release" && docker push "${IMAGE_NAME}:${TRAVIS_COMMIT::8}"
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: chkit set image --deployment docs-production --image "${IMAGE_NAME}:${TRAVIS_COMMIT::8}" --force -n ${NAMESPACE}
    skip_cleanup: true
    on:
      branch: master
