languageCode = "en-us"
title = "Containerum Docs"
# pygmentsStyle = "monokai"
pygmentsUseClassic = true
pygmentsStyle = "monokai"

[params]
  github = "https://github.com/containerum/containerum-docs"
  issue = "Issue with"


[[menu.docs]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"

[[menu.docs]]
  name = "Getting Started"
  weight = 2
  identifier = "getting-started"
  url = "/getting-started/"

[[menu.docs]]
  name = "Containerum"
  weight = 3
  identifier = "platform"
  url = "/platform/"

[[menu.docs]]
  name = "Web Panel"
  weight = 4
  identifier = "web-panel"
  url = "/web-panel/"

[[menu.docs]]
  name = "Kubernetes"
  weight = 5
  identifier = "kubernetes"
  url = "/kubernetes/"

[[menu.docs]]
  name = "CLI"
  weight = 6
  identifier = "cli"
  url = "/cli/"

[[menu.docs]]
  name = "CI/CD"
  weight = 7
  identifier = "ci-cd"
  url = "/ci-cd/"

[[menu.docs]]
  name = "FAQ"
  weight = 8
  identifier = "faq"
  url = "/faq/"

[[menu.docs]]
  name = "Developer Guide - API"
  weight = 9
  identifier = "developer-guide"
  url = "/developer-guide/"

[[menu.docs]]
  name = "Release Notes"
  weight = 10
  identifier = "release-notes"
  url = "/release-notes/"

[[menu.docs]]
  name = "Contribute"
  weight = 11
  identifier = "contribute"
  url = "/contribute/"

[[menu.docs]]
  name = "Commands"
  weight = 12
  identifier = "commands"
  parent = "cli"
  url = "/cli/commands"

[[menu.docs]]
  name = "Components"
  weight = 13
  identifier = "components"
  parent = "platform"
  url = "/platform/components/"

[[menu.docs]]
  name = "Installation"
  weight = 14
  identifier = "installation"
  parent = "kubernetes"
  url = "/kubernetes/installation/"
